[package]
name = "tcal"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = "0.3.2"
ollama-rs-macros = "0.3.2"
schemars = "1.0.3"
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
